enable-chat-messages: true
enable-actionbar-messages: true
blacklist-enabled: false
queue-gui-name: '&9ObsidianAuction Queue'
allow-mobspawners: true
renamed-items-override: false
use-old-bid-logic: false
allow-bid-on-own-auction: false
log-auctions: false
default-starting-bid: 0
max-starting-bid: 100000
default-bid-increment: 1
min-bid-increment: 1
max-bid-increment: 1000
max-buynow: 10000000
expire-buynow-at-first-bid: false
default-auction-time: 300
min-auction-time: 150
max-auction-time: 900
allow-max-bids: true
allow-buynow: true
allow-early-end: false
allow-gamemode-creative: false
allow-damaged-items: false
allow-gamemode-change: false
allow-arenas: false
max-auction-queue-length: 5
min-auction-interval-secs: 10
auction-start-tax: 500
auction-end-tax-percent: 0
deposit-tax-to-user: ''
cancel-prevention-seconds: 15
cancel-prevention-percent: 50
anti-snipe: false
anti-snipe-prevention-seconds: 15
anti-snipe-extension-seconds: 10
allow-sealed-auctions: true
allow-unsealed-auctions: true
allow-renamed-items: true
broadcast-bid-updates: true
allow-auto-bid: true
suppress-countdown: false
allow-inferior-item-name-logic: false
auctionscope-change-check-interval: 20
banned-items:
- 7
- 383;63
taxed-items:
  '0': 100%
disabled-commands-participating:
- /ma join
- /mobarena join
- /arena join
disabled-commands-inscope: {}
banned-lore:
- mcMMO Ability Tool
auction-scopes:
  sspawn_auction_house:
    name: Tower Auctions
    type: house
    house-world: Survival
    house-min-x: -185
    house-min-y: 163
    house-min-z: 193
    house-max-x: -147
    house-max-y: 172
    house-max-z: 230
    config:
      auction-start-tax: 0
  sanctuary_verse:
    name: Sanctuary and related worlds
    type: worlds
    config:
      disabled-commands-inscope: {}
    worlds:
    - Sanctuary
    - Sanctuary_The_End
    - Sanctuary_Nether
  hyperion_verse:
    name: Hyperion, and related worlds
    type: worlds
    config:
      disabled-commands-inscope: {}
    worlds:
    - Hyperion
    - Hyperion_Nether
  survival_verse:
    name: Survival, Empathy, and related worlds
    type: worlds
    worlds:
    - Survival
    - Empathy
    - Survival_Nether
    - Survival_The_End
    - Empathy_the_end
    - Atlas
    config:
      disabled-commands-inscope: {}
name-blacklist:
- porn
- fuck
- shit
- nigger
- cunt
- wetback
- sex
- masturbate
- clop
- penis
- vagina
- wank
- tranny
- ass
- balls
- beaner
- beastiality
- bitch
- cock
- blowjob
- bondage
- busty
- boobs
- tits
- butt
- clit
- coon
- rape
- cum
- faggot
- escort
- hump
- bukkake
- hand job
- handjob
- incest
- pedo
- rapi
- topless
- boner
- shemale
- slut
- fingering
- hentai
- guru
- gay
- dirty
- drug
- cocaine
- marijauna
- undress
- weed
- erotic
- genitals
- xxx
- voyeur
- loli
- jail
- coke
- cocaine
- crack
- mary
- skeet
- hump
- yiffy
